#!/bin/bash
# passwordHashGen
# requires openssl
# Usage:  ./passwordHashGen $PASSWORDTOBEHASHED

# Global variables
SALT=$(ps aux | shuf | md5sum | sed -e 's/ \-//g')

# Password salt generation
openssl passwd -1 -salt $SALT $1
